import type { LauncherApi } from '../shared/ipc.js';
import type { AppState, Shortcut, ShortcutInput, ShortcutType } from '../shared/types.js';

declare global { interface Window { launcher: LauncherApi & { onStateChanged(callback: () => void): () => void }; } }
const root = document.querySelector('#app')!;
let state: AppState;
let page = 'shortcuts';
let editingId: string | undefined;
let onboardingStep = 0;
let selectedMode: 'dashwise' | 'mqtt' = 'dashwise';
let addMenuOpen = false;
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[c]!));
const typeName: Record<ShortcutType, string> = { app: 'Open application', shell: 'Shell command', deeplink: 'Deep link', macro: 'Macro' };
const iconFor = (type: ShortcutType) => ({ app: '▣', shell: '⌁', deeplink: '↗', macro: '✦' }[type]);
function status(status: string, error?: string): string { return `<span class="status-line"><i class="dot ${esc(status)}"></i>${esc(status[0]?.toUpperCase() + status.slice(1))}${error ? ` · ${esc(error)}` : ''}</span>`; }
function render(): void { if (!state.settings.onboardingCompleted) renderOnboarding(); else renderApp(); }
function renderOnboarding(): void {
  const progress = onboardingStep === 0 ? 1 : onboardingStep === 1 ? 2 : 3;
  root.innerHTML = `<div class="onboarding"><div class="onboard"><div class="onboard-top"><div class="brand-mark">D</div><div><strong>Dashwise Desktop Launcher</strong><small>Local shortcuts, ready anywhere</small></div></div><div class="steps"><i class="step done"></i><i class="step ${progress > 1 ? 'done' : 'current'}"></i><i class="step ${progress > 2 ? 'done' : ''}"></i></div>${onboardingStep === 0 ? welcome() : onboardingStep === 1 ? chooseMode() : setupMode()}<div class="onboard-footer">${onboardingStep === 0 ? `<button class="btn primary" data-action="onboard-next">Continue <span>→</span></button>` : onboardingStep === 1 ? `<button class="btn primary" data-action="mode-next">Continue <span>→</span></button>` : `<button class="btn primary" data-action="finish-onboard">Finish setup <span>→</span></button>`}</div></div></div>`;
}
function welcome(): string { return `<section class="welcome"><div class="hero">⚡</div><h1>Your shortcuts,<br>on every surface.</h1><p>Dashwise Desktop Launcher lets Dashwise, Home Assistant and local integrations trigger actions on this computer—securely and instantly.</p></section>`; }
function chooseMode(): string { return `<section><div class="eyebrow">Step 2 of 3</div><h1 class="title">How will you connect?</h1><p class="subtitle">You can change this later in Settings.</p><div class="mode-grid" style="margin-top:27px"><button class="card mode-card ${selectedMode === 'dashwise' ? 'selected' : ''}" data-mode="dashwise"><div class="mode-icon">◈</div><h3>Connect to Dashwise Server</h3><p>Connect this device to an existing Dashwise instance and make its shortcuts available remotely.</p></button><button class="card mode-card disabled" disabled><span class="badge">Coming Soon</span><div class="mode-icon">◇</div><h3>Serverless</h3><p>Use Shortcuts Launcher without a central Dashwise server.</p></button><button class="card mode-card ${selectedMode === 'mqtt' ? 'selected' : ''}" data-mode="mqtt"><div class="mode-icon">⌁</div><h3>MQTT only</h3><p>Connect directly to an MQTT broker and expose shortcuts to Home Assistant.</p></button></div></section>`; }
function setupMode(): string { return selectedMode === 'dashwise' ? `<section><div class="eyebrow">Step 3 of 3 · Dashwise Server</div><h1 class="title">Connect your instance</h1><p class="subtitle">Your authentication token stays on this computer.</p><form class="form" id="onboard-form" style="margin-top:26px"><div class="field"><label>Dashwise server URL</label><input name="serverUrl" placeholder="https://dashwise.example.com" required value="${esc(state.server.serverUrl)}"></div><div class="field"><label>Authentication token</label><input name="authToken" type="password" placeholder="Paste your token" required></div><div class="notice">The launcher will register itself as an on-demand shortcuts app and keep a persistent Activity connection.</div></form></section>` : `<section><div class="eyebrow">Step 3 of 3 · MQTT only</div><h1 class="title">Connect your broker</h1><p class="subtitle">You can configure Home Assistant discovery in settings later.</p><form class="form" id="onboard-form" style="margin-top:26px"><div class="form-row"><div class="field"><label>Broker hostname</label><input name="host" placeholder="homeassistant.local" required value="${esc(state.mqtt.host)}"></div><div class="field"><label>Port</label><input name="port" type="number" value="${state.mqtt.port || 1883}"></div></div><div class="form-row"><div class="field"><label>Username</label><input name="username" value="${esc(state.mqtt.username)}"></div><div class="field"><label>Password</label><input name="password" type="password"></div></div><div class="form-row"><div class="field" style="grid-column:1/-1"><label>Client ID (optional)</label><input name="clientId" placeholder="Auto-generated from this launcher"></div></div><label class="check"><input name="tls" type="checkbox" ${state.mqtt.tls ? 'checked' : ''}> Use TLS encryption</label></form></section>`; }
function sidebar(): string { return `<aside class="sidebar"><nav class="nav"><button class="${page === 'shortcuts' ? 'active' : ''}" data-page="shortcuts">Shortcuts</button><button class="${page === 'mqtt' ? 'active' : ''}" data-page="mqtt">MQTT</button><button class="${page === 'server' ? 'active' : ''}" data-page="server">Your server</button><button class="${page === 'settings' ? 'active' : ''}" data-page="settings">Settings</button></nav><div class="sidebar-footer"><div class="github"><span class="github-mark">●</span> GitHub</div></div></aside>`; }
function renderApp(): void { const title = page === 'shortcuts' ? 'Shortcuts' : page === 'mqtt' ? 'MQTT' : page === 'server' ? 'Your server' : 'Settings'; root.innerHTML = `<div class="desktop"><div class="app-window"><header class="windowbar"><div class="window-brand"><span class="home-icon">⌂</span><span>Launcher</span></div><div class="window-title">${title}</div><div class="window-controls"><button class="window-control close" aria-label="Close" data-action="window-close"></button><button class="window-control minimize" aria-label="Minimize" data-action="window-minimize"></button><button class="window-control maximize" aria-label="Maximize" data-action="window-maximize"></button></div></header><div class="app-body">${sidebar()}<main class="main">${page === 'shortcuts' ? shortcutsPage() : page === 'server' ? serverPage() : page === 'mqtt' ? mqttPage() : settingsPage()}</main></div></div></div>`; }
function shortcutsPage(): string { return `<div class="topline"><div><div class="eyebrow">Your library</div><h1 class="title">Shortcuts</h1><p class="subtitle">Actions that run on this computer, from anywhere.</p></div></div>${state.shortcuts.length ? `<div class="shortcut-grid">${state.shortcuts.map(shortcutCard).join('')}</div>` : `<div class="empty"><div class="empty-icon">✦</div><div style="color:#fff;font-weight:700;margin-bottom:8px">No shortcuts yet</div><div style="margin-bottom:18px">Create a local action to get started.</div></div>`}<div class="add-area">${addMenuOpen ? `<div class="add-menu"><button data-action="new-shortcut-type" data-type="app">Application</button><button data-action="new-shortcut-type" data-type="deeplink">Website</button><button data-action="new-shortcut-type" data-type="macro">Macro</button><button data-action="new-shortcut-type" data-type="deeplink">Deeplink</button><button data-action="new-shortcut-type" data-type="shell">Shell Command</button><button data-action="new-shortcut-type" data-type="macro">Chain Shortcuts</button></div>` : ''}<button class="add-button" aria-label="Add shortcut" data-action="toggle-add">+</button></div>`; }
function shortcutCard(s: Shortcut): string { return `<article class="card shortcut-card"><div class="shortcut-head"><div class="shortcut-icon">${esc(s.icon || iconFor(s.type))}</div><div><div class="shortcut-name">${esc(s.name)}</div><div class="shortcut-type">${esc(typeName[s.type])}</div></div></div><div class="shortcut-actions"><div class="exposure">${s.exposeToDashwise ? '<span class="pill on">Dashwise</span>' : ''}${s.exposeToMqtt ? '<span class="pill on">MQTT</span>' : ''}${!s.exposeToDashwise && !s.exposeToMqtt ? '<span class="pill">Local only</span>' : ''}</div><div class="actions"><button class="btn small" data-action="run" data-id="${esc(s.id)}">Run</button><button class="btn small" data-action="edit" data-id="${esc(s.id)}">Edit</button><button class="btn small" data-action="duplicate" data-id="${esc(s.id)}">Copy</button><button class="btn small" data-action="delete" data-id="${esc(s.id)}">×</button></div></div></article>`; }
function serverPage(): string { const s = state.server; return `<div class="topline"><div><div class="eyebrow">Integration</div><h1 class="title">Dashwise Server</h1><p class="subtitle">Make local shortcuts available through your Dashwise instance.</p></div><div class="actions"><button class="btn" data-action="server-reconnect">Reconnect</button><button class="btn primary" data-action="server-sync">Sync now</button></div></div><div class="integration-grid"><div class="card integration"><div class="eyebrow">Connection</div><h3>${status(s.status, s.lastError)}</h3><p>${esc(s.serverUrl || 'No server configured')}</p><p>Last connected: ${esc(s.connectedAt ? new Date(s.connectedAt).toLocaleString() : 'Never')}</p></div><div class="card integration"><div class="eyebrow">On-demand app</div><h3>${esc(s.shortcutsAppId || 'Not registered')}</h3><p>Exposed shortcuts: ${state.shortcuts.filter((x) => x.exposeToDashwise).length}<br>Last sync: ${esc(s.lastSyncAt ? new Date(s.lastSyncAt).toLocaleString() : 'Never')}</p></div></div><div class="card" style="margin-top:15px"><div class="eyebrow">Server credentials</div><form class="form" id="server-form" style="margin-top:15px"><div class="field"><label>Dashwise server URL</label><input name="serverUrl" required value="${esc(s.serverUrl)}" placeholder="https://dashwise.example.com"></div><div class="field"><label>Authentication token</label><input name="authToken" type="password" required placeholder="Paste a new token"></div><button class="btn primary" style="width:max-content">Save and connect</button></form></div><div class="card" style="margin-top:15px"><div class="eyebrow">Device identity</div><div class="form" style="margin-top:15px"><div class="field"><label>Device / session name</label><input id="device-name" value="${esc(state.settings.deviceName)}"></div><div class="field"><label>Stable session ID</label><input value="${esc(s.sessionId)}" readonly></div><button class="btn primary" style="width:max-content" data-action="save-device">Save name</button></div></div><div class="card" style="margin-top:15px"><button class="btn danger" data-action="server-disconnect">Disconnect server</button><span style="color:var(--muted);font-size:12px;margin-left:13px">Local shortcuts will remain available.</span></div>`; }
function mqttPage(): string { const m = state.mqtt; return `<div class="topline"><div><div class="eyebrow">Integration</div><h1 class="title">MQTT</h1><p class="subtitle">Publish Home Assistant discovery and listen for local shortcut commands.</p></div><div class="actions"><button class="btn" data-action="mqtt-test">Test connection</button><button class="btn primary" data-action="mqtt-save">Save & connect</button></div></div><div class="card"><div style="margin-bottom:18px">${status(m.status, m.lastError)}</div><form class="form" id="mqtt-form"><div class="form-row"><div class="field"><label>Broker hostname</label><input name="host" value="${esc(m.host)}" placeholder="homeassistant.local"></div><div class="field"><label>Port</label><input name="port" type="number" value="${m.port || 1883}"></div></div><div class="form-row"><div class="field"><label>Username</label><input name="username" value="${esc(m.username)}"></div><div class="field"><label>Password</label><input name="password" type="password" placeholder="Leave blank to keep saved password"></div></div><div class="form-row"><div class="field"><label>Client ID</label><input name="clientId" value="${esc(m.clientId)}" placeholder="Auto-generated"></div><label class="check" style="align-self:end"><input name="tls" type="checkbox" ${m.tls ? 'checked' : ''}> Use TLS encryption</label></div></form></div><div class="card" style="margin-top:15px"><div class="eyebrow">Home Assistant discovery</div><h3>${state.shortcuts.filter((x) => x.exposeToMqtt).length} entities published</h3><p class="subtitle">Each exposed shortcut becomes a button on the Dashwise Desktop Launcher device.</p></div>`; }
function settingsPage(): string { return `<div class="topline"><div><div class="eyebrow">Preferences</div><h1 class="title">Settings</h1><p class="subtitle">Choose how the launcher behaves on this computer.</p></div></div><div class="card"><div class="eyebrow">Connection mode</div><div style="font-size:17px;font-weight:750;margin-top:10px">${state.settings.selectedMode === 'dashwise' ? 'Dashwise Server' : 'MQTT only'}</div><p class="subtitle">Serverless mode is not available yet.</p></div><div class="card" style="margin-top:15px"><div class="eyebrow">About</div><h3>Dashwise Desktop Launcher</h3><p class="subtitle">Version 0.1.0 · Local-first shortcut execution</p></div>`; }
function formData(form: HTMLFormElement): Record<string, string | boolean> { const data = new FormData(form), result: Record<string, string | boolean> = {}; for (const [key, value] of data.entries()) result[key] = typeof value === 'string' ? value : true; for (const input of form.querySelectorAll<HTMLInputElement>('input[type=checkbox]')) result[input.name] = input.checked; return result; }
function shortcutModal(id?: string, initialType?: ShortcutType): void { editingId = id; const old = id ? state.shortcuts.find((s) => s.id === id) : undefined; const chosenType = initialType ?? old?.type ?? 'app'; const c = old?.configuration ?? {}; const steps = Array.isArray(c.steps) ? (c.steps as Array<Record<string, unknown>>).map((s) => s.kind === 'delay' ? `delay:${s.ms}` : `shortcut:${s.shortcutId}`).join('\n') : ''; root.insertAdjacentHTML('beforeend', `<div class="modal-wrap" id="shortcut-modal"><div class="modal"><div class="modal-head"><div><div class="eyebrow">${old ? 'Edit shortcut' : 'New shortcut'}</div><h2>${old ? esc(old.name) : 'Create a shortcut'}</h2></div><button class="close" data-action="close-modal">×</button></div><form class="form" id="shortcut-form"><div class="form-row"><div class="field"><label>Name</label><input name="name" required value="${esc(old?.name)}" placeholder="Open my workspace"></div><div class="field"><label>Icon</label><input name="icon" maxlength="2" value="${esc(old?.icon || '⚡')}" placeholder="⚡"></div></div><div class="field"><label>Action type</label><select name="type" id="shortcut-type"><option value="app" ${chosenType === 'app' ? 'selected' : ''}>Open application</option><option value="shell" ${chosenType === 'shell' ? 'selected' : ''}>Shell command</option><option value="deeplink" ${chosenType === 'deeplink' ? 'selected' : ''}>URL / deep link</option><option value="macro" ${chosenType === 'macro' ? 'selected' : ''}>Macro</option></select></div><div id="config-fields"></div><div class="eyebrow">Expose through</div><label class="check"><input name="exposeToDashwise" type="checkbox" ${old?.exposeToDashwise ? 'checked' : ''} ${state.server.serverUrl ? '' : 'disabled'}> Dashwise Server ${state.server.serverUrl ? '' : '<span style="color:var(--muted)">— configure Server first</span>'}</label><label class="check"><input name="exposeToMqtt" type="checkbox" ${old?.exposeToMqtt ? 'checked' : ''} ${state.mqtt.host ? '' : 'disabled'}> Home Assistant / MQTT ${state.mqtt.host ? '' : '<span style="color:var(--muted)">— configure MQTT first</span>'}</label><div class="modal-footer"><button type="button" class="btn" data-action="close-modal">Cancel</button><button class="btn primary">${old ? 'Save changes' : 'Create shortcut'}</button></div></form></div></div>`); const type = document.querySelector<HTMLSelectElement>('#shortcut-type')!; const update = () => { document.querySelector('#config-fields')!.innerHTML = configFields(type.value as ShortcutType, c, steps); }; type.addEventListener('change', update); update(); void window.launcher.listApps().then((apps) => { const list = document.querySelector('#installed-apps'); if (list) list.innerHTML = apps.map((app) => `<option value="${esc(app.name)}">${esc(app.path)}</option>`).join(''); }); }
function configFields(type: ShortcutType, c: Record<string, unknown>, steps: string): string { if (type === 'app') return `<div class="field"><label>Application name</label><input name="appName" list="installed-apps" value="${esc(c.appName)}" placeholder="Visual Studio Code"><datalist id="installed-apps"></datalist></div><div class="field"><label>Application path or executable (optional)</label><input name="path" value="${esc(c.path)}" placeholder="/Applications/Visual Studio Code.app"></div><p class="subtitle">Choose an installed app suggestion or provide an executable / launcher path for this computer.</p>`; if (type === 'shell') return `<div class="notice">Shell shortcuts execute arbitrary commands on this computer. Only create commands you trust.</div><div class="field"><label>Command</label><textarea name="command" required placeholder="npm run dev">${esc(c.command)}</textarea></div><div class="field"><label>Working directory (optional)</label><input name="cwd" value="${esc(c.cwd)}" placeholder="/path/to/project"></div><div class="field"><label>Environment variables (JSON, optional)</label><input name="env" value="${esc(c.env ? JSON.stringify(c.env) : '')}" placeholder='{"MODE":"dev"}'></div>`; if (type === 'deeplink') return `<div class="field"><label>URL or deep link</label><input name="url" required value="${esc(c.url)}" placeholder="https://example.com or obsidian://open"></div>`; return `<div class="field"><label>Macro steps</label><textarea name="stepsText" placeholder="shortcut:existing-shortcut-id\ndelay:1000\nshortcut:another-id">${esc(steps)}</textarea><p class="subtitle">One step per line. Use <code>shortcut:ID</code> to run an existing shortcut or <code>delay:1000</code> to wait in milliseconds.</p></div>`; }
function parseShortcutForm(data: Record<string, string | boolean>): ShortcutInput { const type = data.type as ShortcutType; let configuration: Record<string, unknown> = {}; if (type === 'app') configuration = { appName: data.appName || '', path: data.path || '' }; if (type === 'shell') { let env: unknown = {}; try { env = data.env ? JSON.parse(String(data.env)) : {}; } catch { throw new Error('Environment variables must be valid JSON'); } configuration = { command: data.command || '', cwd: data.cwd || '', env }; } if (type === 'deeplink') configuration = { url: data.url || '' }; if (type === 'macro') configuration = { steps: String(data.stepsText || '').split('\n').map((line) => line.trim()).filter(Boolean).map((line) => line.startsWith('delay:') ? { kind: 'delay', ms: Number(line.slice(6)) || 0 } : { kind: 'shortcut', shortcutId: line.replace(/^shortcut:/, ''), continueOnError: false }) }; return { name: String(data.name || ''), icon: String(data.icon || iconFor(type)), type, configuration, exposeToDashwise: Boolean(data.exposeToDashwise), exposeToMqtt: Boolean(data.exposeToMqtt) }; }
function toast(message: string): void { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.append(node); setTimeout(() => node.remove(), 2600); }
async function refresh(): Promise<void> { state = await window.launcher.getState(); render(); }
document.addEventListener('click', async (event) => { const target = event.target as HTMLElement; const pageButton = target.closest<HTMLElement>('[data-page]'); if (pageButton) { page = pageButton.dataset.page!; render(); return; } const modeButton = target.closest<HTMLElement>('[data-mode]'); if (modeButton) { selectedMode = modeButton.dataset.mode as 'dashwise' | 'mqtt'; render(); return; } const action = target.closest<HTMLElement>('[data-action]'); if (!action) return; const name = action.dataset.action; try {
  if (name === 'window-close') await window.launcher.closeWindow();
  else if (name === 'window-minimize') await window.launcher.minimizeWindow();
  else if (name === 'window-maximize') await window.launcher.toggleMaximizeWindow();
  else if (name === 'onboard-next') { onboardingStep = 1; render(); }
  else if (name === 'mode-next') { onboardingStep = 2; render(); }
  else if (name === 'finish-onboard') { const form = document.querySelector<HTMLFormElement>('#onboard-form'); const data = form ? formData(form) : {}; if (selectedMode === 'dashwise') await window.launcher.configureServer({ serverUrl: String(data.serverUrl || ''), authToken: String(data.authToken || '') }); else await window.launcher.configureMqtt({ host: String(data.host || ''), port: Number(data.port) || 1883, username: String(data.username || ''), password: String(data.password || ''), tls: Boolean(data.tls), clientId: String(data.clientId || '') }); await window.launcher.completeOnboarding(selectedMode); await refresh(); }
  else if (name === 'new-shortcut') shortcutModal();
  else if (name === 'toggle-add') { addMenuOpen = !addMenuOpen; render(); }
  else if (name === 'new-shortcut-type') { addMenuOpen = false; shortcutModal(undefined, action.dataset.type as ShortcutType); }
  else if (name === 'close-modal') document.querySelector('#shortcut-modal')?.remove();
  else if (name === 'run') { const result = await window.launcher.executeShortcut(action.dataset.id!); toast(result.success ? 'Shortcut executed' : result.error || 'Shortcut failed'); }
  else if (name === 'edit') shortcutModal(action.dataset.id);
  else if (name === 'duplicate') { await window.launcher.duplicateShortcut(action.dataset.id!); toast('Shortcut duplicated'); await refresh(); }
  else if (name === 'delete') { const item = state.shortcuts.find((s) => s.id === action.dataset.id); if (item && confirm(`Delete ${item.name}?`)) { await window.launcher.deleteShortcut(item.id); await refresh(); } }
  else if (name === 'server-reconnect') { await window.launcher.reconnectServer(); toast('Reconnecting to Dashwise…'); await refresh(); }
  else if (name === 'server-sync') { await window.launcher.syncServer(); toast('Shortcuts synced'); await refresh(); }
  else if (name === 'server-disconnect') { await window.launcher.disconnectServer(); await refresh(); }
  else if (name === 'save-device') { await window.launcher.setDeviceName(document.querySelector<HTMLInputElement>('#device-name')!.value); toast('Device name saved'); await refresh(); }
  else if (name === 'mqtt-test') { const form = document.querySelector<HTMLFormElement>('#mqtt-form')!, d = formData(form); const result = await window.launcher.testMqtt({ host: String(d.host), port: Number(d.port), username: String(d.username), password: String(d.password), tls: Boolean(d.tls), clientId: String(d.clientId) }); toast(result.success ? 'Connection successful' : result.error || 'Connection failed'); }
  else if (name === 'mqtt-save') { const form = document.querySelector<HTMLFormElement>('#mqtt-form')!, d = formData(form); await window.launcher.configureMqtt({ host: String(d.host), port: Number(d.port), username: String(d.username), password: String(d.password), tls: Boolean(d.tls), clientId: String(d.clientId) }); toast('MQTT saved'); await refresh(); }
 } catch (error) { toast(error instanceof Error ? error.message : String(error)); }
});
document.addEventListener('submit', async (event) => { const form = event.target as HTMLFormElement; event.preventDefault(); try { if (form.id === 'server-form') { const d = formData(form); await window.launcher.configureServer({ serverUrl: String(d.serverUrl), authToken: String(d.authToken) }); toast('Server connection started'); await refresh(); return; } if (form.id !== 'shortcut-form') return; const input = parseShortcutForm(formData(form)); await window.launcher.saveShortcut(input, editingId); document.querySelector('#shortcut-modal')?.remove(); toast(editingId ? 'Shortcut updated' : 'Shortcut created'); editingId = undefined; await refresh(); } catch (error) { toast(error instanceof Error ? error.message : String(error)); } });
window.launcher.onStateChanged(() => void refresh());
void refresh();
